import type {
  Campaign,
  Commodity,
  CommodityId,
  GotongPool,
  HarvestToken,
  LandShare,
  Lesson,
  Listing,
  Person,
  Post,
  TraceStep,
  Tx,
  WeatherDay,
} from "./types";

export const APP_NAME = "AGRI TAPSEL";
export const APP_TAGLINE = "Swasembada Petani Tapsel Bersama RWA";
export const APP_ALT_NAMES = [
  {
    name: "Sahata Tapsel",
    why: "Sahata berarti bersama. Nama ini menempel pada budaya Angkola/Mandailing dan mudah diucapkan petani.",
  },
  {
    name: "Marsipature",
    why: "Dari pepatah Marsipature Huta Na Be — mari kita bangun kampung sendiri. Cocok untuk gerakan regenerasi desa.",
  },
];

export const KECAMATAN = [
  "Sipirok",
  "Marancar",
  "Batang Toru",
  "Muara Batang Toru",
  "Angkola Timur",
  "Angkola Selatan",
  "Angkola Barat",
  "Angkola Sangkunur",
  "Angkola Muara Tais",
  "Batang Angkola",
  "Sayur Matinggi",
  "Tano Tombangan Angkola",
  "Arse",
  "Saipar Dolok Hole",
  "Aek Bilah",
] as const;

export const COMMODITIES: Commodity[] = [
  {
    id: "kopi-arabika",
    name: "Kopi Arabika Sipirok",
    localName: "Kopi dolok",
    unit: "kg",
    tokenUnit: "1 token = 1 kg green bean",
    priceIdr: 92000,
    changePct: 3.4,
    image: "/images/kopi.jpg",
    hub: "Sipirok · Marancar · Arse",
    color: "#2f6b4a",
  },
  {
    id: "kopi-robusta",
    name: "Kopi Robusta",
    localName: "Kopi dataran",
    unit: "kg",
    tokenUnit: "1 token = 1 kg",
    priceIdr: 38500,
    changePct: -1.1,
    image: "/images/kopi.jpg",
    hub: "Batang Angkola · Sayur Matinggi",
    color: "#5c4634",
  },
  {
    id: "kakao",
    name: "Kakao fermentasi",
    localName: "Coklat rakyat",
    unit: "kg",
    tokenUnit: "1 token = 1 kg kering",
    priceIdr: 76500,
    changePct: 5.8,
    image: "/images/kakao.jpg",
    hub: "Marancar · Angkola Timur",
    color: "#6b3a28",
  },
  {
    id: "karet",
    name: "Karet bokar",
    localName: "Getah",
    unit: "kg",
    tokenUnit: "1 token = 1 kg bokar",
    priceIdr: 18200,
    changePct: 1.6,
    image: "/images/karet.jpg",
    hub: "Angkola Sangkunur · Angkola Barat",
    color: "#8a857c",
  },
  {
    id: "sawit",
    name: "Tandan buah sawit",
    localName: "TBS",
    unit: "kg",
    tokenUnit: "1 token = 1 kg TBS",
    priceIdr: 2780,
    changePct: -0.6,
    image: "/images/sawit.jpg",
    hub: "Muara Batang Toru · Angkola Selatan",
    color: "#4a6b2f",
  },
  {
    id: "padi",
    name: "Padi GKP Silatihan",
    localName: "Dahanon",
    unit: "kg",
    tokenUnit: "1 token = 1 kg GKP",
    priceIdr: 6800,
    changePct: 0.8,
    image: "/images/padi.jpg",
    hub: "Sipirok · Batang Angkola",
    color: "#6b8a4a",
  },
  {
    id: "salak",
    name: "Salak Tapsel",
    localName: "Salak",
    unit: "kg",
    tokenUnit: "1 token = 1 kg",
    priceIdr: 12500,
    changePct: 2.2,
    image: "/images/salak.jpg",
    hub: "Angkola · Padang Sidempuan raya",
    color: "#8a6424",
  },
  {
    id: "kulit-manis",
    name: "Kulit manis",
    localName: "Kayu manis",
    unit: "kg",
    tokenUnit: "1 token = 1 kg kulit",
    priceIdr: 48000,
    changePct: 4.1,
    image: "/images/rempah.jpg",
    hub: "Aek Bilah · Saipar Dolok Hole",
    color: "#8a2f2a",
  },
  {
    id: "kemiri",
    name: "Kemiri",
    localName: "Kemiri",
    unit: "kg",
    tokenUnit: "1 token = 1 kg",
    priceIdr: 21500,
    changePct: 0.4,
    image: "/images/rempah.jpg",
    hub: "Sayur Matinggi · Aek Bilah",
    color: "#c4baab",
  },
  {
    id: "aren",
    name: "Gula aren",
    localName: "Gula na togu",
    unit: "kg",
    tokenUnit: "1 token = 1 kg cetak",
    priceIdr: 29500,
    changePct: 2.9,
    image: "/images/rempah.jpg",
    hub: "Sipirok · Arse",
    color: "#5c4634",
  },
];

export const commodityById = Object.fromEntries(
  COMMODITIES.map((c) => [c.id, c]),
) as Record<CommodityId, Commodity>;

export const PEOPLE: Person[] = [
  {
    id: "horas",
    name: "Horas Siregar",
    role: "petani",
    title: "Petani kopi rakyat",
    village: "Bunga Bondar",
    kecamatan: "Sipirok",
    bio: "Mengelola 1,8 ha kopi Arabika di lereng Sibualbuali. Anggota Gapoktan Bunga Bondar.",
  },
  {
    id: "lila",
    name: "Lila Hasibuan",
    role: "investor",
    title: "Diaspora Tapsel · Jakarta",
    village: "Jakarta Selatan",
    kecamatan: "Diaspora",
    bio: "Anak petani Marancar. Membeli token panen kakao untuk keluarga di kampung.",
  },
  {
    id: "nur",
    name: "Nurhayati Nasution",
    role: "koperasi",
    title: "Ketua Koperasi Tani Dolok",
    village: "Hutaraja",
    kecamatan: "Sipirok",
    bio: "Menjaga stok fisik token dan timbang panen anggota.",
  },
  {
    id: "irfan",
    name: "Irfan Pasaribu",
    role: "pemerintah",
    title: "Penyuluh Dinas Pertanian",
    village: "Sipirok",
    kecamatan: "Sipirok",
    bio: "Pendamping desa percontohan dan modul budidaya.",
  },
];

export const INITIAL_TOKENS: HarvestToken[] = [
  {
    id: "TAP-KOPI-00421",
    commodityId: "kopi-arabika",
    qty: 180,
    farmerName: "Horas Siregar",
    village: "Bunga Bondar",
    kecamatan: "Sipirok",
    koperasi: "Koperasi Tani Dolok",
    mintedAt: "2026-08-12T08:20:00+07:00",
    status: "tersimpan",
    txHash: "0x7a3f91c2e8b04d11a55e90c1b8d3f246aa10c9e1",
    grade: "G1 washed · 84,5 SCA",
  },
  {
    id: "TAP-KAKAO-01108",
    commodityId: "kakao",
    qty: 60,
    farmerName: "Horas Siregar",
    village: "Bunga Bondar",
    kecamatan: "Sipirok",
    koperasi: "Koperasi Tani Dolok",
    mintedAt: "2026-07-02T10:05:00+07:00",
    status: "terkunci",
    txHash: "0x12bb77d0c9a14e88f3aa2019c7d55e01b4c8aa22",
    grade: "Fermentasi 5 hari",
  },
];

export const INITIAL_SHARES: LandShare[] = [
  {
    id: "LAHAN-KAKAO-MRC-02",
    title: "Kebun kakao rakyat Marancar Godang",
    commodityId: "kakao",
    village: "Marancar Godang",
    kecamatan: "Marancar",
    hectares: 4.2,
    sharesTotal: 1000,
    sharesOwned: 12,
    pricePerShare: 250000,
    expectedYieldPct: 14,
    koperasi: "Koperasi Kakao Marancar",
  },
];

export const LISTINGS: Listing[] = [
  {
    id: "LST-01",
    commodityId: "kopi-arabika",
    title: "Kopi Arabika G1 Bunga Bondar",
    seller: "Gapoktan Bunga Bondar",
    village: "Bunga Bondar",
    kecamatan: "Sipirok",
    qty: 420,
    priceIdr: 94000,
    grade: "Washed · ketinggian 1.200 mdpl",
    koperasi: "Koperasi Tani Dolok",
    traceId: "TRC-KOPI-421",
    image: "/images/kopi.jpg",
  },
  {
    id: "LST-02",
    commodityId: "kakao",
    title: "Kakao fermentasi Marancar",
    seller: "Kelompok Tani Satahi",
    village: "Marancar Godang",
    kecamatan: "Marancar",
    qty: 310,
    priceIdr: 79000,
    grade: "Fermentasi · kadar air 7%",
    koperasi: "Koperasi Kakao Marancar",
    traceId: "TRC-KAKAO-108",
    image: "/images/kakao.jpg",
  },
  {
    id: "LST-03",
    commodityId: "karet",
    title: "Bokar bersih Angkola Timur",
    seller: "KUD Parsalakan",
    village: "Parsalakan",
    kecamatan: "Angkola Timur",
    qty: 1200,
    priceIdr: 18600,
    grade: "Mutu 2 · tanpa kotoran",
    koperasi: "KUD Parsalakan",
    traceId: "TRC-KARET-033",
    image: "/images/karet.jpg",
  },
  {
    id: "LST-04",
    commodityId: "padi",
    title: "Dahanon Silatihan",
    seller: "Kelompok Tani Silalahi",
    village: "Baringin",
    kecamatan: "Sipirok",
    qty: 800,
    priceIdr: 7200,
    grade: "GKP baru panen",
    koperasi: "Koperasi Tani Dolok",
    traceId: "TRC-PADI-019",
    image: "/images/padi.jpg",
  },
  {
    id: "LST-05",
    commodityId: "aren",
    title: "Gula aren cetak Arse",
    seller: "UMKM Nira Arse",
    village: "Arse",
    kecamatan: "Arse",
    qty: 95,
    priceIdr: 31000,
    grade: "Cetak murni, tanpa pemutih",
    koperasi: "Koperasi Tani Dolok",
    traceId: "TRC-AREN-007",
    image: "/images/rempah.jpg",
  },
  {
    id: "LST-06",
    commodityId: "salak",
    title: "Salak pondoh Tapsel",
    seller: "Poktan Aek Horsik",
    village: "Aek Horsik",
    kecamatan: "Batang Toru",
    qty: 240,
    priceIdr: 13000,
    grade: "Sortir super",
    koperasi: "Koperasi Tani Batang Toru",
    traceId: "TRC-SALAK-012",
    image: "/images/salak.jpg",
  },
];

export const TRACES: Record<string, TraceStep[]> = {
  "TRC-KOPI-421": [
    {
      at: "2026-04-18",
      title: "Tanam & rawat",
      place: "Kebun Horas Siregar · Bunga Bondar",
      note: "Naungan albizia, pupuk kandang, tanpa herbisida.",
    },
    {
      at: "2026-08-04",
      title: "Panen merah",
      place: "Lereng Sibualbuali 1.200 mdpl",
      note: "Petik selektif cherry merah. Timbang 412 kg ceri.",
    },
    {
      at: "2026-08-06",
      title: "Olah washed",
      place: "Unit olah Gapoktan Bunga Bondar",
      note: "Fermentasi 36 jam, jemur para-para sampai KA 11%.",
    },
    {
      at: "2026-08-12",
      title: "Timbang koperasi",
      place: "Koperasi Tani Dolok · Hutaraja",
      note: "180 kg green bean G1 disimpan gudang terkunci.",
    },
    {
      at: "2026-08-12",
      title: "Token diterbitkan",
      place: "Jaringan Polygon (amat sangat murah)",
      note: "1 token = 1 kg. Dijamin stok fisik koperasi.",
    },
  ],
  "TRC-KAKAO-108": [
    {
      at: "2026-03-02",
      title: "Kebun rakyat",
      place: "Marancar Godang",
      note: "Kakao lindung, tumpang sari pisang.",
    },
    {
      at: "2026-06-28",
      title: "Panen & belah",
      place: "Kebun Satahi",
      note: "Pod masak pohon, belah hari yang sama.",
    },
    {
      at: "2026-07-02",
      title: "Fermentasi kotak",
      place: "Rumah fermentasi kelompok",
      note: "5 hari, dibalik 2 kali, dijemur anyaman.",
    },
    {
      at: "2026-07-02",
      title: "Token diterbitkan",
      place: "Koperasi Kakao Marancar",
      note: "Stok 310 kg masuk gudang resi.",
    },
  ],
};

export const POSTS: Post[] = [
  {
    id: "p1",
    author: "Horas Siregar",
    roleLabel: "Petani kopi",
    village: "Bunga Bondar",
    kecamatan: "Sipirok",
    body: "Hujan semalam bagus untuk dolok, tapi jemur para-para kami terpaksa ditunda. Ada yang punya terpal cadangan di Hutaraja?",
    topic: "Kopi",
    likes: 24,
    comments: 7,
    liked: false,
    createdAt: "2026-09-19T06:40:00+07:00",
  },
  {
    id: "p2",
    author: "Sari Lubis",
    roleLabel: "Petani milenial",
    village: "Marancar Godang",
    kecamatan: "Marancar",
    body: "Anak muda Marancar mulai fermentasi kakao bareng. Jangan jual basah ke tengkulak kalau bisa diolah. Harga beda jauh.",
    topic: "Kakao",
    likes: 41,
    comments: 12,
    liked: true,
    createdAt: "2026-09-18T19:12:00+07:00",
  },
  {
    id: "p3",
    author: "Pak Usman Harahap",
    roleLabel: "Ketua kelompok",
    village: "Parsalakan",
    kecamatan: "Angkola Timur",
    body: "Gotong royong pupuk karet minggu ini. Yang belum setor iuran digital, bisa di aplikasi. Jangan malu, patungan itu adat kita.",
    topic: "Gotong royong",
    likes: 33,
    comments: 5,
    liked: false,
    createdAt: "2026-09-18T11:05:00+07:00",
  },
  {
    id: "p4",
    author: "Irfan Pasaribu",
    roleLabel: "Penyuluh",
    village: "Sipirok",
    kecamatan: "Sipirok",
    body: "Dinas buka kelas budidaya kopi Sambung Pucuk, Kamis sore di kantor kecamatan. Bawa contoh ranting. Gratis untuk anggota gapoktan.",
    topic: "Edukasi",
    likes: 18,
    comments: 4,
    liked: false,
    createdAt: "2026-09-17T15:30:00+07:00",
  },
];

export const POOLS: GotongPool[] = [
  {
    id: "GR-01",
    title: "Patungan pupuk kopi Bunga Bondar",
    purpose: "Pupuk organik & kapur dolomit untuk 28 kebun.",
    village: "Bunga Bondar, Sipirok",
    targetIdr: 14000000,
    raisedIdr: 9200000,
    members: 22,
    due: "2026-09-28",
    joined: true,
  },
  {
    id: "GR-02",
    title: "Mesin belah kakao Marancar",
    purpose: "Beli 1 unit pemecah pod agar olah lebih cepat.",
    village: "Marancar Godang",
    targetIdr: 8500000,
    raisedIdr: 3100000,
    members: 11,
    due: "2026-10-12",
    joined: false,
  },
  {
    id: "GR-03",
    title: "Terpal jemur bersama Parsalakan",
    purpose: "12 terpal untuk bokar dan padi musim hujan.",
    village: "Parsalakan, Angkola Timur",
    targetIdr: 4800000,
    raisedIdr: 4100000,
    members: 19,
    due: "2026-09-24",
    joined: false,
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: "CF-01",
    title: "Biaya panen kopi Sipirok 2026",
    commodityId: "kopi-arabika",
    village: "Bunga Bondar",
    kecamatan: "Sipirok",
    story:
      "Gapoktan butuh upah petik dan olah washed sebelum harga naik di musim puncak. Investor membeli token panen di muka. Setelah jual, hasil dibagi lewat perjanjian yang sudah tertulis.",
    targetIdr: 75000000,
    raisedIdr: 48200000,
    investors: 37,
    sharePct: 18,
    tenorMonths: 5,
    risk: "rendah",
    image: "/images/kopi.jpg",
  },
  {
    id: "CF-02",
    title: "Rumah fermentasi kakao Marancar",
    commodityId: "kakao",
    village: "Marancar Godang",
    kecamatan: "Marancar",
    story:
      "Membangun kotak fermentasi dan lantai jemur supaya petani tidak jual basah. Bagi hasil dari selisih harga fermentasi vs non-fermentasi.",
    targetIdr: 120000000,
    raisedIdr: 44500000,
    investors: 21,
    sharePct: 22,
    tenorMonths: 12,
    risk: "sedang",
    image: "/images/kakao.jpg",
  },
  {
    id: "CF-03",
    title: "Gula aren cetak Arse",
    commodityId: "aren",
    village: "Arse",
    kecamatan: "Arse",
    story:
      "Modal nira, cetakan, dan kemasan untuk 12 penyadap. Pembeli setuju harga kontrak 6 bulan.",
    targetIdr: 40000000,
    raisedIdr: 26800000,
    investors: 15,
    sharePct: 16,
    tenorMonths: 6,
    risk: "rendah",
    image: "/images/rempah.jpg",
  },
];

export const LESSONS: Lesson[] = [
  {
    slug: "kopi-petik-merah",
    title: "Petik merah, jangan petik hijau",
    minutes: 8,
    category: "Kopi",
    summary: "Cara sederhana menaikkan harga kopi tanpa pupuk mahal.",
    body: [
      "Kopi Sipirok mahal kalau bijinya masak benar. Petik hanya buah yang merah. Campur hijau membuat rasa asam dan harga jatuh.",
      "Di dolok, satu pohon bisa dipetik 3–4 kali. Jangan buru-buru habiskan. Upah petik lebih kecil dibanding selisih harga G1.",
      "Setelah petik, olah di kelompok. Washed (cuci) atau honey, pilih satu dan jaga bersih. Jangan jemur di aspal.",
    ],
    terms: [
      { batak: "Dolok", arti: "Gunung / dataran tinggi" },
      { batak: "Dongan sabutuha", arti: "Kerabat, kawan seasal" },
    ],
  },
  {
    slug: "kakao-jangan-basah",
    title: "Kakao: jangan jual basah",
    minutes: 10,
    category: "Kakao",
    summary: "Fermentasi 5 hari mengubah harga tengkulak jadi harga pasar.",
    body: [
      "Kakao basah dibeli murah karena pembeli yang menanggung risiko olah. Kalau kelompok punya kotak fermentasi, nilai tertahan di desa.",
      "Belah buah hari panen. Masukkan biji ke kotak kayu, tutup karung goni, balik hari ke-2 dan ke-4. Jemur sampai kering benar.",
      "Simpan di gudang koperasi, lalu terbitkan token. Pembeli jauh bisa bayar tanpa datang, stok tetap di Marancar.",
    ],
    terms: [{ batak: "Satahi", arti: "Seia sekata, kompak" }],
  },
  {
    slug: "uang-digital-aman",
    title: "Uang digital yang aman untuk petani",
    minutes: 7,
    category: "Keuangan",
    summary: "QRIS, dompet, dan token — dijelaskan tanpa istilah susah.",
    body: [
      "Dompet di AGRI TAPSEL seperti buku kas. Rupiah masuk-keluar tercatat. Token bukan uang mainan: tiap token mewakili kilo panen di gudang koperasi.",
      "Jangan berikan PIN ke siapa pun, termasuk anak kandung yang meminjam HP. Ubah PIN di balai desa jika HP hilang.",
      "Kalau ragu, tanya penyuluh atau ketua koperasi. Jangan transfer ke orang tak dikenal yang menjanjikan 'token berlipat'.",
    ],
    terms: [{ batak: "Hamoraon", arti: "Kemakmuran, harta yang berkah" }],
  },
  {
    slug: "gotong-royong-digital",
    title: "Gotong royong di HP",
    minutes: 6,
    category: "Komunitas",
    summary: "Patungan pupuk dan alat tanpa ribut catatan kertas.",
    body: [
      "Adat kita sudah patungan. Aplikasi hanya membuat iuran kelihatan: siapa sudah setor, berapa kurang, kapan barang datang.",
      "Ketua kelompok membuka kumpulan. Anggota masuk sesuai kemampuan. Tidak ada bunga. Sisa dana kembali ke kas kelompok.",
      "Ini bukan utang rentenir. Ini marharoan yang dicatat rapi.",
    ],
    terms: [
      { batak: "Marharoan", arti: "Bekerja / menolong bersama" },
      { batak: "Huta", arti: "Kampung / desa" },
    ],
  },
  {
    slug: "iklim-tapsel",
    title: "Musim kering di Tapsel",
    minutes: 9,
    category: "Iklim",
    summary: "Apa yang dilakukan jika hujan lama tak datang.",
    body: [
      "Lereng Sipirok basah, tapi El Niño bisa menunda hujan. Kopi muda rontok jika tanah pecah. Mulsa daun dan rorak penampung air membantu.",
      "Jangan bakar semak. Akar tertahan, tanah tidak terbang. Tanam penaung pelan-pelan.",
      "Pantau ramalan 7 hari di menu Cuaca. Jika 10 hari tanpa hujan, tunda pemupukan urea.",
    ],
    terms: [{ batak: "Aek", arti: "Air / sungai" }],
  },
];

export const WEATHER: WeatherDay[] = [
  { day: "Min", temp: 22, rainMm: 8, label: "Gerimis" },
  { day: "Sen", temp: 23, rainMm: 18, label: "Hujan" },
  { day: "Sel", temp: 24, rainMm: 2, label: "Cerah" },
  { day: "Rab", temp: 23, rainMm: 12, label: "Hujan" },
  { day: "Kam", temp: 22, rainMm: 4, label: "Berawan" },
  { day: "Jum", temp: 21, rainMm: 0, label: "Cerah" },
  { day: "Sab", temp: 22, rainMm: 6, label: "Gerimis" },
];

export const PRICE_SERIES: { minggu: string; kopi: number; kakao: number; karet: number }[] = [
  { minggu: "Mei", kopi: 84000, kakao: 68000, karet: 16800 },
  { minggu: "Jun", kopi: 86000, kakao: 70000, karet: 17100 },
  { minggu: "Jul", kopi: 89000, kakao: 72000, karet: 17600 },
  { minggu: "Agu", kopi: 87500, kakao: 74000, karet: 17900 },
  { minggu: "Sep", kopi: 92000, kakao: 76500, karet: 18200 },
];

export const INITIAL_TX: Tx[] = [
  {
    id: "tx1",
    at: "2026-09-18T09:10:00+07:00",
    label: "Jual 20 kg kopi ke Koperasi Tani Dolok",
    amountIdr: 1840000,
    kind: "masuk",
  },
  {
    id: "tx2",
    at: "2026-09-16T14:02:00+07:00",
    label: "Iuran gotong royong pupuk",
    amountIdr: 150000,
    kind: "keluar",
  },
  {
    id: "tx3",
    at: "2026-09-12T08:44:00+07:00",
    label: "Bantuan pupuk Dinas (QRIS)",
    amountIdr: 500000,
    kind: "masuk",
  },
];

export const BADGES = [
  { id: "b1", name: "Petik Merah", desc: "3 musim petik selektif" },
  { id: "b2", name: "Dongan Setia", desc: "Aktif di 5 gotong royong" },
  { id: "b3", name: "Gudang Jujur", desc: "Selisih timbang < 1%" },
];

export const KOPERASI_STOCK = [
  { commodityId: "kopi-arabika" as CommodityId, kg: 1840, tokens: 1840 },
  { commodityId: "kakao" as CommodityId, kg: 620, tokens: 620 },
  { commodityId: "padi" as CommodityId, kg: 2400, tokens: 2400 },
  { commodityId: "aren" as CommodityId, kg: 180, tokens: 180 },
];

export const VILLAGE_STATS = [
  { desa: "Bunga Bondar", kec: "Sipirok", petani: 86, token: 42, aktif: true },
  { desa: "Hutaraja", kec: "Sipirok", petani: 54, token: 21, aktif: true },
  { desa: "Marancar Godang", kec: "Marancar", petani: 71, token: 18, aktif: true },
  { desa: "Parsalakan", kec: "Angkola Timur", petani: 63, token: 9, aktif: true },
  { desa: "Arse", kec: "Arse", petani: 40, token: 6, aktif: false },
  { desa: "Aek Horsik", kec: "Batang Toru", petani: 48, token: 4, aktif: false },
];

export const CALC_PRESETS: Record<
  CommodityId,
  { costPerHa: number; yieldKg: number; months: number; note: string }
> = {
  "kopi-arabika": {
    costPerHa: 18500000,
    yieldKg: 800,
    months: 12,
    note: "Produksi kebun rakyat dolok, sudah menghasilkan.",
  },
  "kopi-robusta": { costPerHa: 14200000, yieldKg: 1100, months: 12, note: "Dataran lebih rendah." },
  kakao: { costPerHa: 16800000, yieldKg: 700, months: 12, note: "Setelah fermentasi." },
  karet: { costPerHa: 9800000, yieldKg: 1200, months: 12, note: "Sadap 3 hari sekali." },
  sawit: { costPerHa: 22000000, yieldKg: 14000, months: 12, note: "TBS rakyat, bukan CPO." },
  padi: { costPerHa: 12500000, yieldKg: 4800, months: 4, note: "Satu musim GKP." },
  salak: { costPerHa: 15000000, yieldKg: 8000, months: 12, note: "Setelah tanaman menghasilkan." },
  "kulit-manis": { costPerHa: 9000000, yieldKg: 600, months: 18, note: "Panen kulit berselang." },
  kemiri: { costPerHa: 7200000, yieldKg: 900, months: 12, note: "Pohon campuran." },
  aren: { costPerHa: 11000000, yieldKg: 1500, months: 12, note: "Nira jadi gula cetak." },
};
