/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BelajarRouteImport } from './routes/belajar'
import { Route as CuacaRouteImport } from './routes/cuaca'
import { Route as DanaRouteImport } from './routes/dana'
import { Route as DompetRouteImport } from './routes/dompet'
import { Route as GotongRouteImport } from './routes/gotong'
import { Route as HitungRouteImport } from './routes/hitung'
import { Route as KomunitasRouteImport } from './routes/komunitas'
import { Route as KonsepRouteImport } from './routes/konsep'
import { Route as MulaiRouteImport } from './routes/mulai'
import { Route as PasarRouteImport } from './routes/pasar'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as TokenRouteImport } from './routes/token'
import { Route as BelajarIndexRouteImport } from './routes/belajar.index'
import { Route as BelajarSlugRouteImport } from './routes/belajar.$slug'
import { Route as DanaIndexRouteImport } from './routes/dana.index'
import { Route as DanaIdRouteImport } from './routes/dana.$id'
import { Route as PasarIndexRouteImport } from './routes/pasar.index'
import { Route as PasarIdRouteImport } from './routes/pasar.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarRoute = BelajarRouteImport.update({
  id: '/belajar',
  path: '/belajar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuacaRoute = CuacaRouteImport.update({
  id: '/cuaca',
  path: '/cuaca',
  getParentRoute: () => rootRouteImport,
} as any)
const DanaRoute = DanaRouteImport.update({
  id: '/dana',
  path: '/dana',
  getParentRoute: () => rootRouteImport,
} as any)
const DompetRoute = DompetRouteImport.update({
  id: '/dompet',
  path: '/dompet',
  getParentRoute: () => rootRouteImport,
} as any)
const GotongRoute = GotongRouteImport.update({
  id: '/gotong',
  path: '/gotong',
  getParentRoute: () => rootRouteImport,
} as any)
const HitungRoute = HitungRouteImport.update({
  id: '/hitung',
  path: '/hitung',
  getParentRoute: () => rootRouteImport,
} as any)
const KomunitasRoute = KomunitasRouteImport.update({
  id: '/komunitas',
  path: '/komunitas',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsepRoute = KonsepRouteImport.update({
  id: '/konsep',
  path: '/konsep',
  getParentRoute: () => rootRouteImport,
} as any)
const MulaiRoute = MulaiRouteImport.update({
  id: '/mulai',
  path: '/mulai',
  getParentRoute: () => rootRouteImport,
} as any)
const PasarRoute = PasarRouteImport.update({
  id: '/pasar',
  path: '/pasar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarIndexRoute = BelajarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BelajarRoute,
} as any)
const BelajarSlugRoute = BelajarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BelajarRoute,
} as any)
const DanaIndexRoute = DanaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DanaRoute,
} as any)
const DanaIdRoute = DanaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DanaRoute,
} as any)
const PasarIndexRoute = PasarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PasarRoute,
} as any)
const PasarIdRoute = PasarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PasarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/belajar': typeof BelajarRouteWithChildren
  '/cuaca': typeof CuacaRoute
  '/dana': typeof DanaRouteWithChildren
  '/dompet': typeof DompetRoute
  '/gotong': typeof GotongRoute
  '/hitung': typeof HitungRoute
  '/komunitas': typeof KomunitasRoute
  '/konsep': typeof KonsepRoute
  '/mulai': typeof MulaiRoute
  '/pasar': typeof PasarRouteWithChildren
  '/profil': typeof ProfilRoute
  '/token': typeof TokenRoute
  '/belajar/$slug': typeof BelajarSlugRoute
  '/dana/$id': typeof DanaIdRoute
  '/pasar/$id': typeof PasarIdRoute
  '/belajar/': typeof BelajarIndexRoute
  '/dana/': typeof DanaIndexRoute
  '/pasar/': typeof PasarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuaca': typeof CuacaRoute
  '/dompet': typeof DompetRoute
  '/gotong': typeof GotongRoute
  '/hitung': typeof HitungRoute
  '/komunitas': typeof KomunitasRoute
  '/konsep': typeof KonsepRoute
  '/mulai': typeof MulaiRoute
  '/profil': typeof ProfilRoute
  '/token': typeof TokenRoute
  '/belajar/$slug': typeof BelajarSlugRoute
  '/dana/$id': typeof DanaIdRoute
  '/pasar/$id': typeof PasarIdRoute
  '/belajar': typeof BelajarIndexRoute
  '/dana': typeof DanaIndexRoute
  '/pasar': typeof PasarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/belajar': typeof BelajarRouteWithChildren
  '/cuaca': typeof CuacaRoute
  '/dana': typeof DanaRouteWithChildren
  '/dompet': typeof DompetRoute
  '/gotong': typeof GotongRoute
  '/hitung': typeof HitungRoute
  '/komunitas': typeof KomunitasRoute
  '/konsep': typeof KonsepRoute
  '/mulai': typeof MulaiRoute
  '/pasar': typeof PasarRouteWithChildren
  '/profil': typeof ProfilRoute
  '/token': typeof TokenRoute
  '/belajar/$slug': typeof BelajarSlugRoute
  '/dana/$id': typeof DanaIdRoute
  '/pasar/$id': typeof PasarIdRoute
  '/belajar/': typeof BelajarIndexRoute
  '/dana/': typeof DanaIndexRoute
  '/pasar/': typeof PasarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/belajar'
    | '/cuaca'
    | '/dana'
    | '/dompet'
    | '/gotong'
    | '/hitung'
    | '/komunitas'
    | '/konsep'
    | '/mulai'
    | '/pasar'
    | '/profil'
    | '/token'
    | '/belajar/$slug'
    | '/dana/$id'
    | '/pasar/$id'
    | '/belajar/'
    | '/dana/'
    | '/pasar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuaca'
    | '/dompet'
    | '/gotong'
    | '/hitung'
    | '/komunitas'
    | '/konsep'
    | '/mulai'
    | '/profil'
    | '/token'
    | '/belajar/$slug'
    | '/dana/$id'
    | '/pasar/$id'
    | '/belajar'
    | '/dana'
    | '/pasar'
  id:
    | '__root__'
    | '/'
    | '/belajar'
    | '/cuaca'
    | '/dana'
    | '/dompet'
    | '/gotong'
    | '/hitung'
    | '/komunitas'
    | '/konsep'
    | '/mulai'
    | '/pasar'
    | '/profil'
    | '/token'
    | '/belajar/$slug'
    | '/dana/$id'
    | '/pasar/$id'
    | '/belajar/'
    | '/dana/'
    | '/pasar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BelajarRoute: typeof BelajarRouteWithChildren
  CuacaRoute: typeof CuacaRoute
  DanaRoute: typeof DanaRouteWithChildren
  DompetRoute: typeof DompetRoute
  GotongRoute: typeof GotongRoute
  HitungRoute: typeof HitungRoute
  KomunitasRoute: typeof KomunitasRoute
  KonsepRoute: typeof KonsepRoute
  MulaiRoute: typeof MulaiRoute
  PasarRoute: typeof PasarRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  TokenRoute: typeof TokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar': {
      id: '/belajar'
      path: '/belajar'
      fullPath: '/belajar'
      preLoaderRoute: typeof BelajarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuaca': {
      id: '/cuaca'
      path: '/cuaca'
      fullPath: '/cuaca'
      preLoaderRoute: typeof CuacaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dana': {
      id: '/dana'
      path: '/dana'
      fullPath: '/dana'
      preLoaderRoute: typeof DanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dompet': {
      id: '/dompet'
      path: '/dompet'
      fullPath: '/dompet'
      preLoaderRoute: typeof DompetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gotong': {
      id: '/gotong'
      path: '/gotong'
      fullPath: '/gotong'
      preLoaderRoute: typeof GotongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitung': {
      id: '/hitung'
      path: '/hitung'
      fullPath: '/hitung'
      preLoaderRoute: typeof HitungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komunitas': {
      id: '/komunitas'
      path: '/komunitas'
      fullPath: '/komunitas'
      preLoaderRoute: typeof KomunitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsep': {
      id: '/konsep'
      path: '/konsep'
      fullPath: '/konsep'
      preLoaderRoute: typeof KonsepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mulai': {
      id: '/mulai'
      path: '/mulai'
      fullPath: '/mulai'
      preLoaderRoute: typeof MulaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasar': {
      id: '/pasar'
      path: '/pasar'
      fullPath: '/pasar'
      preLoaderRoute: typeof PasarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar/': {
      id: '/belajar/'
      path: '/'
      fullPath: '/belajar/'
      preLoaderRoute: typeof BelajarIndexRouteImport
      parentRoute: typeof BelajarRoute
    }
    '/belajar/$slug': {
      id: '/belajar/$slug'
      path: '/$slug'
      fullPath: '/belajar/$slug'
      preLoaderRoute: typeof BelajarSlugRouteImport
      parentRoute: typeof BelajarRoute
    }
    '/dana/': {
      id: '/dana/'
      path: '/'
      fullPath: '/dana/'
      preLoaderRoute: typeof DanaIndexRouteImport
      parentRoute: typeof DanaRoute
    }
    '/dana/$id': {
      id: '/dana/$id'
      path: '/$id'
      fullPath: '/dana/$id'
      preLoaderRoute: typeof DanaIdRouteImport
      parentRoute: typeof DanaRoute
    }
    '/pasar/': {
      id: '/pasar/'
      path: '/'
      fullPath: '/pasar/'
      preLoaderRoute: typeof PasarIndexRouteImport
      parentRoute: typeof PasarRoute
    }
    '/pasar/$id': {
      id: '/pasar/$id'
      path: '/$id'
      fullPath: '/pasar/$id'
      preLoaderRoute: typeof PasarIdRouteImport
      parentRoute: typeof PasarRoute
    }
  }
}

interface BelajarRouteChildren {
  BelajarSlugRoute: typeof BelajarSlugRoute
  BelajarIndexRoute: typeof BelajarIndexRoute
}

const BelajarRouteChildren: BelajarRouteChildren = {
  BelajarSlugRoute: BelajarSlugRoute,
  BelajarIndexRoute: BelajarIndexRoute,
}

const BelajarRouteWithChildren =
  BelajarRoute._addFileChildren(BelajarRouteChildren)

interface DanaRouteChildren {
  DanaIdRoute: typeof DanaIdRoute
  DanaIndexRoute: typeof DanaIndexRoute
}

const DanaRouteChildren: DanaRouteChildren = {
  DanaIdRoute: DanaIdRoute,
  DanaIndexRoute: DanaIndexRoute,
}

const DanaRouteWithChildren = DanaRoute._addFileChildren(DanaRouteChildren)

interface PasarRouteChildren {
  PasarIdRoute: typeof PasarIdRoute
  PasarIndexRoute: typeof PasarIndexRoute
}

const PasarRouteChildren: PasarRouteChildren = {
  PasarIdRoute: PasarIdRoute,
  PasarIndexRoute: PasarIndexRoute,
}

const PasarRouteWithChildren = PasarRoute._addFileChildren(PasarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BelajarRoute: BelajarRouteWithChildren,
  CuacaRoute: CuacaRoute,
  DanaRoute: DanaRouteWithChildren,
  DompetRoute: DompetRoute,
  GotongRoute: GotongRoute,
  HitungRoute: HitungRoute,
  KomunitasRoute: KomunitasRoute,
  KonsepRoute: KonsepRoute,
  MulaiRoute: MulaiRoute,
  PasarRoute: PasarRouteWithChildren,
  ProfilRoute: ProfilRoute,
  TokenRoute: TokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
